#!/bin/bash
echo "----------------------------------------------------"
virsh list --all
echo "----------------------------------------------------"
echo -n "功能区：" 
echo -e "\033[33m""
    创建一台虚拟机请输入： create
    批量启动虚拟机请输入： start
    批量关闭虚拟机请输入： stop
    批量重启虚拟机请输入： restart
    批量删除虚拟机请输入： remove
""\033[39m""----------------------------------------------------"
if [ $# -eq 0 ];then
  read -p "请根据需求输入选项： " op
else
  op=$1
fi
case $op in 
create)
  /root/Scripts-vm-copy/vm-copy;;
start)
  read -p "请输入需要开启的机器(多个以空格分隔): " pon
  for i in  $pon   
  do
      virsh start $i
  done;;
stop)
  read -p "请输入需要关闭的机器(多个以空格分隔): " poff
  for j in  $poff
  do
      virsh destroy $j
  done;;
restart)
  read -p "请输入需要重启的机器(多个以空格分隔): " res
  for k in  $res
  do
      virsh destroy $k \
      && virsh start $k \
      && echo -e "\033[33m""虚拟机${k}已经重新启动!""\033[39m"
  done;;
remove)
  while :
  do
    read -p "请输入需要删除的虚拟机名称(多个以空格分隔): " name
    if [ "$name" == ""  ];then
        echo -e "\033[31m输入不能为空,请重新输入\033[39m"
        continue
    fi
    a=0
    for vm in $name
    do
        if [ ! -e "/etc/libvirt/qemu/${vm}.xml" ];then
            echo -e "\033[31m虚拟机${vm}不存在,请重新输入\033[39m"
            a=1
        fi
    done
    if [ $a -eq 0  ];then
        break
    fi
  done
  for vm in $name
  do
    virsh destroy $vm &> /dev/null
    for img in $(sed -rn "/source file/s/([^']+)'(.*)'.*/\2/p" /etc/libvirt/qemu/${vm}.xml)
    do
        rm -rf $img
    done
    virsh undefine $vm &> /dev/null && echo -e "\033[31m"">>>>> 虚拟机${vm}已经从系统删除!""\033[39m"
done;;
*)
  echo -e "\033[33m""输入内容不匹配！""\033[39m";;
esac
