#!/bin/bash
virsh list --all
while :
do
    read -p "请输入需要删除的虚拟机名称(多个请以空格隔开): " name
    if [ "$name" == ""  ];then
        echo -e "\033[31m输入不能为空,请重新输入\033[39m"
        continue
    fi
    a=0
    for vm in $name
    do
        if [ ! -e "/etc/libvirt/qemu/${vm}.xml" ];then
            echo -e "\033[31m虚拟机${vm}不存在,请重新输入\033[39m"
            a=1
        fi
    done
    if [ $a -eq 0  ];then
        break
    fi 
done
for vm in $name
do
    virsh destroy $vm &> /dev/null 
    for img in $(sed -rn "/source file/s/([^']+)'(.*)'.*/\2/p" /etc/libvirt/qemu/${vm}.xml)
    do
        rm -rf $img
    done
    virsh undefine $vm &> /dev/null && echo -e "\033[31m"">>>>> 虚拟机${vm}已经从系统删除!""\033[39m"
done
