#!/bin/bash
vmls () {
echo "----------------------------------------------------"
virsh list --all
echo "----------------------------------------------------"
}
funls () {
echo -n "功能区：" 
echo -e "\033[33m""
    创建一台虚拟机请输入： create
    批量启动虚拟机请输入： start
    批量关闭虚拟机请输入： stop
    批量重启虚拟机请输入： restart
    批量删除虚拟机请输入： remove
""\033[39m""----------------------------------------------------"
}
oh=0
if [ $# -eq 0 ];then
  vmls
  oh=1
  funls
  read -p "请根据需求输入选项： " op
else
  op=$1
fi
case $op in 
create)
  /root/Scripts-vm-copy/vm-copy2;;
start)
  if [ -z $2 ];then
    [ $oh -eq 1 ] || vmls
    read -p "请输入需要开启的机器(多个以空格分隔): " pon
  else
    pon=$2
  fi
  for i in  $pon   
  do
      virsh start $i
  done;;
stop)
  if [ -z $2 ];then
    [ $oh -eq 1 ] || vmls
    read -p "请输入需要关闭的机器(多个以空格分隔): " poff
  else
    poff=$2
  fi
  for j in  $poff
  do
    # virsh destroy $j
    virsh shutdown $j
  done;;
restart)
  if [ -z $2 ];then
    [ $oh -eq 1 ] || vmls
    read -p "请输入需要重启的机器(多个以空格分隔): " res
  else
    res=$2
  fi
  for k in  $res
  do
      virsh destroy $k \
      && virsh start $k \
      && echo -e "\033[33m""虚拟机${k}已经重新启动!""\033[39m"
  done;;
remove)
  if [ -z $2 ];then
    [ $oh -eq 1 ] || vmls
    while :
    do
      read -p "请输入需要删除的虚拟机名称(多个以空格分隔): " name
      if [ "$name" == ""  ];then
          echo -e "\033[31m输入不能为空,请重新输入\033[39m"
          continue
      fi
      a=0
      for vm in $name
      do
          if [ ! -e "/etc/libvirt/qemu/${vm}.xml" ];then
              echo -e "\033[31m虚拟机${vm}不存在,请重新输入\033[39m"
              a=1
          fi
      done
      if [ $a -eq 0  ];then
          break
      fi
    done
  else
  name=$2
  fi
  for vm in $name
  do
    virsh destroy $vm &> /dev/null
    for img in $(sed -rn "/source file/s/([^']+)'(.*)'.*/\2/p" /etc/libvirt/qemu/${vm}.xml)
    do
        rm -rf $img
    done
    virsh undefine $vm &> /dev/null && echo -e "\033[31m"">>>>> 虚拟机${vm}已经从系统删除!""\033[39m"
done;;
list)
  [ $oh -eq 1 ] || vmls;;
--help)
cat << EOF
命令格式: vmbox [list|create|start|stop|restart|remove] <虚拟机名称>
选项说明:
    list        后面不需要参数,相当于virsh list --all命令,显示所有虚拟机状态。
    create      创建新的虚拟机,此命令带来的增益效果具体请参照manual.txt文件说明。
    start       开启虚拟机,可实现批量启动。当后面有参数时,可以实现快速启动单台虚拟机。
    stop        关闭虚拟机,可实现批量关闭。当后面有参数时，可以实现快速关闭单台虚拟机。
    restart     重启虚拟机,可实现批量重启。当后面有参数时,可以实现快速重启单台虚拟机。
    remove      删除虚拟机，可实现批量删除虚拟机。当后面有参数时，可以实现快速删除单台虚拟机。
EOF
;; 
*)
  echo -e "\033[33m""输入内容不匹配！""\033[39m";;
esac
